### ISSUE TITLE
Fix SSL bug in Res uploading to Testmine

### ISSUE THREAD

**Issue by wordswords** [bbc/hive-ci#49]
Testmine was moved over to the tools.bbc.co.uk space, and during that http support was disabled in favour of https/ssl. 

There now is a problem where the 'res' results uploader doesn't have the code required for SSL support for uploading to Testmine. 

This should be a fairly easy fix which will allow us to use Testmine again on the Hive, which will be very useful for recording reliablity statistics for the TVAPI Control Tests.

**Comment by wordswords** [comment]
I have located the section of the code which I need to edit, it's not currently working, but nearly there.

**Comment by Asimk21** [comment]
Fixed in bbc/res#93
