### ISSUE TITLE
Put scripts in version control

### ISSUE THREAD

**Issue by wordswords** [bbc/hive-ci#53]
As a user of the Hive I often have to edit the scripts on the Hive. Sometimes I want to recall a previous version of the script to see what has changed, or want to know who has changed the script. If I can't do this it often means lengthy debugging time, as I wait for the Hive to process a new job and run through the new script. 

I think this process could be made easier by putting some kind of version control around the Hive scripts. Whenever a script is updated it is saved in version control. Ideally this would be in a github repo, but any kind of version control would be an improvement, if we don't have enough time to sync it with github.

**Comment by davidbuckhurst** [comment]
Can't you just use version control? You could just check in an execution script to your test directory and call that from the hive script template?

**Comment by wordswords** [comment]
We could but it is quite messy. We would have to pass all the environment variables to that script, and the team has agreed that it would be much nicer if it was just in that script window so everyone can tell when the scripts change, and what has changed.

**Comment by wordswords** [comment]
We have decided to use version control after all as we don't have time to add a feature to the Hive.

Next step is to put all the TVAPI scripts from the Hive CI script into their own seperate file and run it from that file.
